name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build blockkit-ts dependency
        run: npm run build --workspace=blockkit-ts

      - name: Build blockkit-ts examples
        run: npm run build:example --workspace=blockkit-ts

      - name: Build game
        run: npm run build --workspace=game

      - name: Create combined site structure
        run: |
          mkdir -p combined-site
          cp -r game/dist/* combined-site/
          mkdir -p combined-site/blockkit
          cp -r blockkit-ts/dist-example/* combined-site/blockkit/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: combined-site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
